apiVersion: app/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: golelena99/python-app:1.0
        ports:
        - containerPort: 8000
